##
## CopyPackage.cmake: This file is part of libport.
## Copyright (C) Gostai S.A.S., 2006-2008.
##
## This software is provided "as is" without warranty of any kind,
## either expressed or implied, including but not limited to the
## implied warranties of fitness for a particular purpose.
##
## See the LICENSE file for more information.
## For comments, bug reports and feedback: http://www.urbiforge.com
##

# Copy all packages generated by cpack in CMAKE_BINARY_DIR to DESTDIR.

include("${CMAKE_BINARY_DIR}/CPackConfig.cmake")

file(GLOB list "${CMAKE_BINARY_DIR}/${CPACK_PACKAGE_FILE_NAME}.*")
foreach(i ${list})
  execute_process(
    COMMAND ${CMAKE_COMMAND} -E copy ${i} ${DESTDIR}
    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
    RESULT_VARIABLE ret
  )
  if(ret)
    message(SEND_ERROR "Failed to copy '${i}' to '${DESTDIR}'")
  else(ret)
    message(STATUS "Successfully copy '${i}' to '${DESTDIR}'")
  endif(ret)
endforeach(i)
