#! /bin/sh
#
# Copyright (c) Gostai S.A.S., 2006.
#
# This software is provided "as is" without warranty of any kind,
# either expressed or implied, including but not limited to the
# implied warranties of fitness for a particular purpose.
#
# See the LICENSE file for more information.
# For comments, bug reports and feedback: http://www.urbiforge.org

export LIBTOOLIZE_FLAGS="--ltdl --nonrecursive"
exec build-aux/bin/bootstrap "$@"
