#! /bin/sh
#
# Fix libtool .la file so that .dll/.lib files are organized into the
# right section on Windows.
#
# Usage: fix-libtool-la <la-file> <stamp-file>
#
# The time stamp of the <la-file> will be preserved. The file will not
# be modified unless a .dll is being installed.
#
# In any case, this will touch the stamp file with the current date.
#

set -e

lafile=$1
stampfile=$2

rm -f "$stampfile" "$stampfile.tmp"
touch "$stampfile.tmp"

library_names=$(sed -ne "s/^library_names='\\(.*\\)'/\\1/p" < "$lafile")
set x $library_names
shift
echo >&2 "$0: libnames: $@"
case $1:$2 in
    *.dll:*.lib)
	library_names=$1
	old_library=$2
	tmpfile=$lafile.tmp
	sed -e "s/^library_names=.*/library_names='$library_names'/" \
	    -e "s/^old_library=.*/old_library='$old_library'/" < "$lafile" \
	    > "$tmpfile"
	touch --reference="$lafile" "$tmpfile"
	mv "$tmpfile" "$lafile"
	;;
    *)
	;;
esac

mv "$stampfile.tmp" "$stampfile"
