#! /bin/sh
#
# Fix libtool .la file so that .dll/.lib files are organized into the
# right section on Windows.
#
# Usage: fix-libtool-la <la-file> <stamp-file>
#
# The time stamp of the <la-file> will be preserved. The file will not
# be modified unless a .dll is being installed.
#
# In any case, this will touch the stamp file with the current date.
#

set -e

me=$(basename "$0")

stderr ()
{
  local i
  for i
  do
    echo >&2 "$me: $i"
  done
}

run ()
{
  stderr "run: $*"
  "$@"
}

lafile=$1
stampfile=$2

rm -f "$stampfile" "$stampfile.tmp"
touch "$stampfile.tmp"

library_names=$(sed -ne "s/^library_names='\\(.*\\)'/\\1/p" < "$lafile")
set x $library_names
shift
stderr "libnames for $lafile: $*"
case $1:$2 in
    (*.dll:*.lib)
	library_names=$1
	old_library=$2
        mv "$lafile" "$lafile.bak"
        {
          echo "# Modified by $me"
	  sed -e "s/^library_names=.*/# &\nlibrary_names='$library_names'/"  \
	      -e "s/^old_library=.*/# &\nold_library='$old_library'/"        \
              "$lafile.bak"
        } >"$lafile"
	touch --reference="$lafile.bak" "$lafile"
        run diff -u "$lafile.bak" "$lafile" || true
	;;
esac

mv "$stampfile.tmp" "$stampfile"
