#!/bin/sh
##
## move-if-change: This file is part of build-aux.
## Copyright (C) Gostai S.A.S., 2006-2008.
##
## This software is provided "as is" without warranty of any kind,
## either expressed or implied, including but not limited to the
## implied warranties of fitness for a particular purpose.
##
## See the LICENSE file for more information.
## For comments, bug reports and feedback: http://www.urbiforge.com
##

# Like mv $1 $2, but if the files are the same, just delete $1.
# Status is 0 if $2 is changed, 1 otherwise.

if test -r "$2"; then
    if cmp -s "$1" "$2"; then
	echo >&2 "$2 is unchanged"
	rm -f "$1"
    else
	mv -f "$1" "$2"
    fi
else
    mv -f "$1" "$2"
fi
