#!/bin/sh
##
## move-if-change: This file is part of build-aux.
## Copyright (C) 2006-2009, Gostai S.A.S.
##
## This software is provided "as is" without warranty of any kind,
## either expressed or implied, including but not limited to the
## implied warranties of fitness for a particular purpose.
##
## See the LICENSE file for more information.
## For comments, bug reports and feedback: http://www.urbiforge.com
##

# Like mv $1 $2, but if the files are the same, just delete $1.
# Status is 0 if $2 is changed, 1 otherwise.

diff="diff -q"
echo=echo

usage ()
{
  cat <<EOF
usage: $0 [OPTION...] SOURCE DESTINATION

Rename SOURCE as DESTINATION, but preserve the timestamps of
DESTINATION if SOURCE and DESTINATION have equal contents.

Options:
  -h, --help        display this message and exit
  -I, --ignore-matching-lines REGEXP
                    ignore differences in lines matching REGEXP
  -s, --silent      do not report anything
EOF
  exit 0
}

while test $# != 0
do
  case $1 in
    (-h|--help)
      usage ;;

    (-I|--ignore-matching-lines)
      shift
      diff+=" -I $1";;

    (-s|--silent)
      echo=:
      ;;

    (*)
      if test -z "$from"; then
        from=$1
      else
        to=$1
      fi
      ;;
  esac
  shift
done

if test -r "$to" && $diff "$from" "$to"; then
  $echo >&2 "$to is unchanged"
  # The file might have actually changed, but changes that are
  # ignored.  In that case, we want the latest contents, but the
  # oldest time stamp.  Since mv preserves time stamps, just set the
  # time stamps of the new one to that of the old one.
  touch -r "$to" "$from"
fi
mv -f "$from" "$to"
