#! /bin/sh
##
## rename: This file is part of build-aux.
## Copyright (C) 2006-2008, Gostai S.A.S.
##
## This software is provided "as is" without warranty of any kind,
## either expressed or implied, including but not limited to the
## implied warranties of fitness for a particular purpose.
##
## See the LICENSE file for more information.
## For comments, bug reports and feedback: http://www.urbiforge.com
##


set -x

# rename header HEADER.H
# ----------------------
# Rename HEADER.H to HEADER.Hh
rename ()
{
  header=$1
  perl -pi -e "s/\\\\file +$header\\b/\\\\file ${header}h/g;" \
	   -e 's/_H(_DEFINED)?$/_HH/g;' \
	$header
  perl -pi -e "s/(#[ \\t]*include \"$header)\"/\${1}h\"/g" *[ch]
  perl -pi -e "s/$header/${header}h/g" Makefile.am
  svn mv --force $i ${i}h
}

for i in *.h
do
  rename $i
done
