#!/usr/bin/env ruby
##
## move-if-change: This file is part of build-aux.
## Copyright (C) 2006-2008, Gostai S.A.S.
##
## This software is provided "as is" without warranty of any kind,
## either expressed or implied, including but not limited to the
## implied warranties of fitness for a particular purpose.
##
## See the LICENSE file for more information.
## For comments, bug reports and feedback: http://www.urbiforge.com
##

# Like mv $1 $2, but if the files are the same, just delete $1.
# Status is 0 if $2 is changed, 1 otherwise.

require 'fileutils'

if File.readable?(ARGV[1])
  if FileUtils.compare_file(ARGV[0], ARGV[1])
    STDERR.puts("#{ARGV[1]} is unchanged")
    FileUtils.rm_rf(ARGV[0])
  else
    FileUtils.mv(ARGV[0], ARGV[1], :force => true)
  end
else
  FileUtils.mv(ARGV[0], ARGV[1], :force => true)
end

